In [16]:
import os
import numpy as np
import json

In [17]:
# Get the current working directory
CURRENT_DIRECTORY = os.getcwd()
# Get the parent directory
PARENT_DIRECTORY = os.path.dirname(CURRENT_DIRECTORY)
PARENT_DIRECTORY = os.path.dirname(PARENT_DIRECTORY)

# Open the config file and load its content into a dictionary
config_file = open(PARENT_DIRECTORY + '\\config\\config.json')
CONFIG_DATA = json.load(config_file)

# Close the file after loading the data
config_file.close()

In [18]:
REST_LPITCH = CONFIG_DATA["REST_LPITCH"]
REST_LROLL = CONFIG_DATA["REST_LROLL"]
REST_RPITCH = CONFIG_DATA["REST_RPITCH"]
REST_RROLL = CONFIG_DATA["REST_RROLL"]

ALL_X_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-X-TRAIN-CLASSIFY-MOTIONTYPE-STEPS-V0.npy'
ALL_Y_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-Y-TRAIN-CLASSIFY-MOTIONTYPE-STEPS-V0.npy'
ALL_X_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-X-TEST-CLASSIFY-MOTIONTYPE-STEPS-V0.npy'
ALL_Y_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-Y-TEST-CLASSIFY-MOTIONTYPE-STEPS-V0.npy'


NEW_ALL_X_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-X-TRAIN-CLASSIFY-MOTIONTYPE-STEPS-V4.npy'
NEW_ALL_Y_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-Y-TRAIN-CLASSIFY-MOTIONTYPE-STEPS-V4.npy'
NEW_ALL_X_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-X-TEST-CLASSIFY-MOTIONTYPE-STEPS-V4.npy'
NEW_ALL_Y_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-Y-TEST-CLASSIFY-MOTIONTYPE-STEPS-V4.npy'


In [19]:
ALL_X_TRAIN_DATA = np.load(ALL_X_TRAINING_DATA_PATH)
ALL_Y_TRAIN_DATA = np.load(ALL_Y_TRAINING_DATA_PATH)

ALL_X_TEST_DATA = np.load(ALL_X_TEST_DATA_PATH)
ALL_Y_TEST_DATA = np.load(ALL_Y_TEST_DATA_PATH)

print(ALL_X_TRAIN_DATA[0:10, :])

[[18.  3. 43. -1.]
 [18.  3. 43. -1.]
 [18.  3. 43. -1.]
 [18.  3. 43. -1.]
 [18.  2. 43. -1.]
 [18.  2. 43. -1.]
 [18.  2. 43. -1.]
 [18.  2. 43. -1.]
 [18.  2. 43. -1.]
 [19.  2. 43. -1.]]


In [20]:
ALL_X_TRAIN_DATA[:, 0] = ALL_X_TRAIN_DATA[:, 0] - REST_LPITCH
ALL_X_TRAIN_DATA[:, 1] = ALL_X_TRAIN_DATA[:, 1] - REST_LROLL
ALL_X_TRAIN_DATA[:, 2] = ALL_X_TRAIN_DATA[:, 2] - REST_RPITCH
ALL_X_TRAIN_DATA[:, 3] = ALL_X_TRAIN_DATA[:, 3] - REST_RROLL

print(ALL_X_TRAIN_DATA[0:10, :])

[[ 0.  0. 26.  1.]
 [ 0.  0. 26.  1.]
 [ 0.  0. 26.  1.]
 [ 0.  0. 26.  1.]
 [ 0. -1. 26.  1.]
 [ 0. -1. 26.  1.]
 [ 0. -1. 26.  1.]
 [ 0. -1. 26.  1.]
 [ 0. -1. 26.  1.]
 [ 1. -1. 26.  1.]]


In [21]:
print(ALL_X_TEST_DATA[0:10, :])

ALL_X_TEST_DATA[:, 0] = ALL_X_TEST_DATA[:, 0] - REST_LPITCH
ALL_X_TEST_DATA[:, 1] = ALL_X_TEST_DATA[:, 1] - REST_LROLL
ALL_X_TEST_DATA[:, 2] = ALL_X_TEST_DATA[:, 2] - REST_RPITCH
ALL_X_TEST_DATA[:, 3] = ALL_X_TEST_DATA[:, 3] - REST_RROLL

print(ALL_X_TEST_DATA[0:10, :])

[[24. 10. 26. -1.]
 [24. 10. 26. -1.]
 [24. 10. 28. -1.]
 [24. 10. 28. -1.]
 [24. 10. 28. -1.]
 [24. 10. 31. -1.]
 [24. 10. 36. -1.]
 [22. 10. 38. -1.]
 [21.  8. 42. -1.]
 [19.  3. 42. -1.]]
[[ 6.  7.  9.  1.]
 [ 6.  7.  9.  1.]
 [ 6.  7. 11.  1.]
 [ 6.  7. 11.  1.]
 [ 6.  7. 11.  1.]
 [ 6.  7. 14.  1.]
 [ 6.  7. 19.  1.]
 [ 4.  7. 21.  1.]
 [ 3.  5. 25.  1.]
 [ 1.  0. 25.  1.]]


In [22]:
np.save(NEW_ALL_X_TRAINING_DATA_PATH, ALL_X_TRAIN_DATA)
np.save(NEW_ALL_Y_TRAINING_DATA_PATH, ALL_Y_TRAIN_DATA)
np.save(NEW_ALL_X_TEST_DATA_PATH, ALL_X_TEST_DATA)
np.save(NEW_ALL_Y_TEST_DATA_PATH, ALL_Y_TEST_DATA)