In [1]:
import os
import numpy as np
import json

In [2]:
# Get the current working directory
CURRENT_DIRECTORY = os.getcwd()
# Get the parent directory
PARENT_DIRECTORY = os.path.dirname(CURRENT_DIRECTORY)
PARENT_DIRECTORY = os.path.dirname(PARENT_DIRECTORY)

# Open the config file and load its content into a dictionary
config_file = open(PARENT_DIRECTORY + '\\config\\config.json')
CONFIG_DATA = json.load(config_file)

# Close the file after loading the data
config_file.close()

In [3]:
REST_LPITCH = CONFIG_DATA["REST_LPITCH"]
REST_LROLL = CONFIG_DATA["REST_LROLL"]
REST_RPITCH = CONFIG_DATA["REST_RPITCH"]
REST_RROLL = CONFIG_DATA["REST_RROLL"]

ALL_X_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-X-TRAIN-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V0.npy'
ALL_Y_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-Y-TRAIN-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V0.npy'
ALL_X_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-X-TEST-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V0.npy'
ALL_Y_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-Y-TEST-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V0.npy'


NEW_ALL_X_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-X-TRAIN-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V4.npy'
NEW_ALL_Y_TRAINING_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\training\\ALL-Y-TRAIN-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V4.npy'
NEW_ALL_X_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-X-TEST-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V4.npy'
NEW_ALL_Y_TEST_DATA_PATH = PARENT_DIRECTORY + '\\NeuralNetwork\\np-saved-data\\test\\ALL-Y-TEST-CLASSIFY-MOTIONTYPE-LSIDESTEPS-V4.npy'


In [9]:
ALL_X_TRAIN_DATA = np.load(ALL_X_TRAINING_DATA_PATH)
ALL_Y_TRAIN_DATA = np.load(ALL_Y_TRAINING_DATA_PATH)

ALL_X_TEST_DATA = np.load(ALL_X_TEST_DATA_PATH)
ALL_Y_TEST_DATA = np.load(ALL_Y_TEST_DATA_PATH)

print(ALL_X_TRAIN_DATA[0:10, :])

[[ 13. -18.  19.  -5.  28.   4.  21.  -3.]
 [ 13. -18.  19.  -5.  28.   4.  21.  -3.]
 [ 13. -18.  19.  -5.  28.   9.  21.  -3.]
 [ 13. -18.  19.  -5.  28.  15.  21.  -3.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -3.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -3.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -3.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -2.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -1.]
 [ 13. -18.  19.  -5.  28.  17.  21.  -1.]]


In [10]:
ALL_X_TRAIN_DATA[:, 0] = ALL_X_TRAIN_DATA[:, 0] - REST_LPITCH
ALL_X_TRAIN_DATA[:, 1] = ALL_X_TRAIN_DATA[:, 1] - REST_LROLL
ALL_X_TRAIN_DATA[:, 2] = ALL_X_TRAIN_DATA[:, 2] - REST_RPITCH
ALL_X_TRAIN_DATA[:, 3] = ALL_X_TRAIN_DATA[:, 3] - REST_RROLL

ALL_X_TRAIN_DATA[:, 4] = ALL_X_TRAIN_DATA[:, 4] - REST_LPITCH
ALL_X_TRAIN_DATA[:, 5] = ALL_X_TRAIN_DATA[:, 5] - REST_LROLL
ALL_X_TRAIN_DATA[:, 6] = ALL_X_TRAIN_DATA[:, 6] - REST_RPITCH
ALL_X_TRAIN_DATA[:, 7] = ALL_X_TRAIN_DATA[:, 7] - REST_RROLL


print(ALL_X_TRAIN_DATA[0:10, :])

[[ -5. -21.   2.  -3.  10.   1.   4.  -1.]
 [ -5. -21.   2.  -3.  10.   1.   4.  -1.]
 [ -5. -21.   2.  -3.  10.   6.   4.  -1.]
 [ -5. -21.   2.  -3.  10.  12.   4.  -1.]
 [ -5. -21.   2.  -3.  10.  14.   4.  -1.]
 [ -5. -21.   2.  -3.  10.  14.   4.  -1.]
 [ -5. -21.   2.  -3.  10.  14.   4.  -1.]
 [ -5. -21.   2.  -3.  10.  14.   4.   0.]
 [ -5. -21.   2.  -3.  10.  14.   4.   1.]
 [ -5. -21.   2.  -3.  10.  14.   4.   1.]]


In [11]:
print(ALL_X_TEST_DATA[0:10, :])

ALL_X_TEST_DATA[:, 0] = ALL_X_TEST_DATA[:, 0] - REST_LPITCH
ALL_X_TEST_DATA[:, 1] = ALL_X_TEST_DATA[:, 1] - REST_LROLL
ALL_X_TEST_DATA[:, 2] = ALL_X_TEST_DATA[:, 2] - REST_RPITCH
ALL_X_TEST_DATA[:, 3] = ALL_X_TEST_DATA[:, 3] - REST_RROLL

ALL_X_TEST_DATA[:, 4] = ALL_X_TEST_DATA[:, 4] - REST_LPITCH
ALL_X_TEST_DATA[:, 5] = ALL_X_TEST_DATA[:, 5] - REST_LROLL
ALL_X_TEST_DATA[:, 6] = ALL_X_TEST_DATA[:, 6] - REST_RPITCH
ALL_X_TEST_DATA[:, 7] = ALL_X_TEST_DATA[:, 7] - REST_RROLL

print(ALL_X_TEST_DATA[0:10, :])

[[ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 19. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 17. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 17. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 17. -13.  18.  -4.  28.  17.  20.  -1.]
 [ 17. -13.  18.  -4.  28.  17.  20.  -1.]]
[[  1. -16.   1.  -2.  10.  14.   3.   1.]
 [  1. -16.   1.  -2.  10.  14.   3.   1.]
 [  1. -16.   1.  -2.  10.  14.   3.   1.]
 [  1. -16.   1.  -2.  10.  14.   3.   1.]
 [  1. -16.   1.  -2.  10.  14.   3.   1.]
 [  1. -16.   1.  -2.  10.  14.   3.   1.]
 [ -1. -16.   1.  -2.  10.  14.   3.   1.]
 [ -1. -16.   1.  -2.  10.  14.   3.   1.]
 [ -1. -16.   1.  -2.  10.  14.   3.   1.]
 [ -1. -16.   1.  -2.  10.  14.   3.   1.]]


In [22]:
np.save(NEW_ALL_X_TRAINING_DATA_PATH, ALL_X_TRAIN_DATA)
np.save(NEW_ALL_Y_TRAINING_DATA_PATH, ALL_Y_TRAIN_DATA)
np.save(NEW_ALL_X_TEST_DATA_PATH, ALL_X_TEST_DATA)
np.save(NEW_ALL_Y_TEST_DATA_PATH, ALL_Y_TEST_DATA)